services:
  app:
    build: .
    restart: always
    ports:
      - "8080:80"
    networks:
      - sistema-tareas-bot-supabase-ojj6pm_default

networks:
  sistema-tareas-bot-supabase-ojj6pm_default:
    external: true
