services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    restart: always

# El servicio estará disponible en http://localhost:8080
