name: Notificador Diario Tareas UNEMI

on:
  schedule:
    # 16:00 UTC es igual a las 11:00 AM en Ecuador (GMT-5)
    - cron: '0 16 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub para probar

jobs:
  ping_notificador:
    runs-on: ubuntu-latest
    steps:
      - name: Despertar y Ejecutar Notificador
        run: |
          curl --location --request GET 'https://sistema-tareas-4g94.onrender.com/notificador.php?token=ClaveUnemi123' \
          --header 'User-Agent: GitHubAction-Notificador' \
          --verbose
